# Generated by Django 5.0.7 on 2024-07-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingTable',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='MenuTable',
            new_name='Menu',
        ),
    ]
